LogiSync/LogiSync/Controllers/PersonalController.cs
using LogiSync.Models;
using Microsoft.AspNetCore.Mvc;
using System.Web.Mvc;

namespace LogiSync.Controllers
{
    public class PersonalController : Controller
    {

        //AppDbContext _context;

        //public PersonalController(AppDbContext context)
        //{
        //    _context = context;
        //}

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult RegistroPersonal()
        {
            return View();
        }

        //[HttpPost]
        //public IActionResult RegistrarPersonal([Bind()] Personal personal)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        if (personal != null)
        //        {
        //            var temp = _context.personal.FirtsOrDefault(x => x.cedula.Equals(personal.Cedula));

        //            if (temp == null)
        //            {
        //                _context.personal.Add(temp);
        //                _context.SaveChange();

        //                return RedirectToAction("Index", "Administrador");
        //            } 
        //            else
        //            {
        //                TempData["PersonalError"] = "Ya existe un personal con esa cédula. Intente nuevamente.";
        //                return View();
        //            }
        //        }
        //        else
        //        {
        //            TempData["PersonalError"] = "Error al registrar el personal. Comuniquese con el administrador.";
        //            return View();
        //        }
        //    }
        //    else
        //    {
        //        TempData["PersonalError"] = "Debe de llenar todos los campos.";
        //        return View();
        //    }
        //}

        [HttpGet]
        public IActionResult ExcluirPersonal()
        {
            return View();
        }

        //[HttpPost]
        //public IActionResult ExcluirPersonal([Bind()] Personal personal)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        if (personal != null)
        //        {
        //            var temp = _context.personal.FirtsOrDefault(x => x.cedula.Equals(personal.Cedula));

        //            if (temp != null)
        //            {
        //                _context.ChangeTracker.Clear();
        //                _context.personal.Update(temp);
        //                _context.SaveChange();

        //                return RedirectToAction("Index", "Administrador");
        //            }
        //            else
        //            {
        //                TempData["PersonalError"] = "No existe un personal con esa cédula. Intente nuevamente.";
        //                return View();
        //            }
        //        }
        //        else
        //        {
        //            TempData["PersonalError"] = "Error al excluir el personal. Comuniquese con el administrador.";
        //            return View();
        //        }
        //    }
        //    else
        //    {
        //        TempData["PersonalError"] = "Debe de llenar todos los campos.";
        //        return View();
        //    }
        //}

        [HttpGet]
        public IActionResult BuscarPersonal()
        {
            return View();
        }

        [HttpPost]
        public Iactionresult buscarpersonal([bind()] personal personal)
        {
            if (!modelstate.isvalid)
            {
                if (personal != null)
                {
                    var temp = _context.personal.firtsordefault(x => x.cedula.equals(personal.cedula));

                    if (temp != null)
                    {
                        return view (temp);
                    }
                   else
                    {
                        tempdata["personalerror"] = "no existe un personal con esa cédula. intente nuevamente.";
                        return view();
                    }
                }
                else
                {
                    tempdata["personalerror"] = "error al buscar el personal. comuniquese con el administrador.";
                    return view();
                }
            }
            else
            {
                tempdata["personalerror"] = "debe de llenar todos los campos.";
                return view();
           }
        }

        [HttpGet]
        public IActionResult ModificarPersonal()
        {
            return View();
        }

        //[HttpPost]
        //public IActionResult ModificarPersonal([Bind()] Personal personal)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        if (personal != null)
        //        {
        //            var temp = _context.personal.FirtsOrDefault(x => x.cedula.Equals(personal.Cedula));

        //            if (temp != null)
        //            {
        //                _context.ChangeTracker.Clear();
        //                _context.personal.Update(temp);
        //                _context.SaveChange();

        //                return RedirectToAction("Index", "Administrador");
        //            }
        //            else
        //            {
        //                TempData["PersonalError"] = "No existe un personal con esa cédula. Intente nuevamente.";
        //                return View();
        //            }
        //        }
        //        else
        //        {
        //            TempData["PersonalError"] = "Error al modificar el personal. Comuniquese con el administrador.";
        //            return View();
        //        }
        //    }
        //    else
        //    {
        //        TempData["PersonalError"] = "Debe de llenar todos los campos.";
        //        return View();
        //    }
        //}
    }
}

LogiSync/LogiSync/Controllers/UsuarioController.cs
using LogiSync.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LogiSync.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        //--------------------------------------------------

        private string GenerarClave()
        {
            Random randow = new Random();
            string clave = string.Empty;
            clave = "ABCDEFGHIJKLMNOPQRSTUVWQXZ0123456789";
            return new string(Enumerable.Repeat(clave, 12).Select(s => s[randow.Next(s.Length)]).ToArray());
        }

        //--------------------------------------------------


        [HttpGet]
        public IActionResult CrearUsuario()
        {
            return View();
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult CrearCuenta([Bind] Usuario user)
        //{
        //    if (user != null)
        //    {
               

        //        //Se le asigna una password temporal
        //        user.Password = this.GenerarClave();
        //        _context.Usuarios.Add(user);

        //        try
        //        {
        //            _context.SaveChanges();
        //            if (this.EnviarEmail(user))
        //            {
        //                TempData["MensajeCreado"] = "Usuario creado correctamente. Su contraseña fue enviada por email.";
        //            }
        //            else
        //            {
        //                TempData["MensajeCreado"] = "Usuario creado pero no fue posible enviar el correo. Comuníquese con el administrador.";
        //            }

        //        }
        //        catch (Exception ex)
        //        {
        //            TempData["MensajeCreado"] = "No se logró crear la cuenta..." + ex.Message;
        //        }
        //        return View();
        //    }
        //    else
        //    {
        //        TempData["MensajeCreado"] = "No se logró crear la cuenta...";
        //        return View();
        //    }
        //}



        //--------------------------------------------------
    }
}

LogiSync/LogiSync/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LogiSync</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LogiSync.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">LogiSync</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Gestión de personal
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Personal" asp-action="RegistroPersonal">Registrar</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Personal" asp-action="ModificarPersonal">Modificar</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Personal" asp-action="ExcluirPersonal">Excluir</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Personal" asp-action="BuscarPersonal">Buscar</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="CrearUsuario">Crear Usuario</a>
                                </li>
                            
                            </ul>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-white btn btn-primary" id="BotonCerrar" asp-area="" asp-controller="Usuario" asp-action="Login">Iniciar sesión</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>